name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get pnpm version from package.json
        id: pnpm-version
        shell: bash
        run: echo "pnpm_version=$(node -p 'require(`./package.json`).engines.pnpm')" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with typechecking and coverage
        run: pnpm run test

      - name: Run type checks
        run: pnpm exec tsc --noEmit

      - name: Run linting
        run: pnpm lint

      - name: Build and check package types
        run: pnpm build && pnpm exec attw --pack --profile=node16